-- App sync table --
CREATE TABLE
    public.gl_sync
(
    id         uuid                     not null default gen_random_uuid(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    deleted    boolean                  null     default false,
    sync_id    smallint                 not null default 1,
    updater    text                     not null,
    constraint gl_sync_pkey primary key (id),
    constraint gl_sync_sync_id_key unique (sync_id),
    constraint gl_sync_is_singleton check (sync_id = 1)
) TABLESPACE pg_default;

ALTER TABLE public.gl_sync
    ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER handle_times
    BEFORE INSERT
        OR
        UPDATE
    ON gl_sync
    FOR each row
execute function handle_times();

CREATE POLICY allow_public_users_to_select
    ON public.gl_sync
    FOR SELECT
    using (public.is_public_user());

-- App version table --
CREATE TABLE
    public.gl_versions
(
    id           uuid                                     not null default gen_random_uuid(),
    created_at   timestamp with time zone                 not null default now(),
    updated_at   timestamp with time zone                 not null default now(),
    deleted      boolean                                  null     default false,
    version_id   integer generated by default as identity not null,
    version      text                                     not null,
    version_info text                                     null,
    constraint gl_version_pkey primary key (id),
    constraint gl_versions_version_id_key unique (version_id)
) tablespace pg_default;

ALTER TABLE public.gl_versions
    ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER handle_times
    BEFORE INSERT
        OR
        UPDATE
    ON gl_versions
    FOR each row
execute function handle_times();

CREATE POLICY allow_public_users_to_select
    ON public.gl_versions
    FOR SELECT
    using (public.is_public_user());

